# Generated by Django 2.2.6 on 2019-12-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('status', models.CharField(max_length=30)),
                ('crn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.FloatField()),
                ('type', models.CharField(max_length=10)),
                ('instructor', models.CharField(max_length=30)),
                ('days', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('reqs', models.CharField(max_length=100)),
                ('length', models.FloatField()),
            ],
        ),
    ]
